name: quant-finance-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - yfinance
  - pandas-datareader
  - jupyterlab
  - tqdm
  - openpyxl
  - cvxpy
  - quantstats
  - empyrical
  - ffn
  - xgboost
  - lightgbm
  - shap
  - ipython
  - pip  # Needed for installing pip-only packages
  - pip:
      - arch
      - nolds
      - pyfolio